### PR TITLE
apply formatter changes

### PR DESCRIPTION
**Pull request by themegaphoenix**
One of many PR request to come.

This makes it to adhere to Python standards regarding formatting

### CODE REVIEW

**Comment by itsToggle** [comment]
Sounds like a good idea, thanks! I would like to keep the importing of modules inside the try/catch block, since a lot of inexperienced users contacted me that they didn't know what to do with the standard python "missing module" error. Aside from that it's probably a good idea to do a lint check.

**Comment by themegaphoenix** [comment]
> Sounds like a good idea, thanks! I would like to keep the importing of modules inside the try/catch block, since a lot of inexperienced users contacted me that they didn't know what to do with the standard python "missing module" error. Aside from that it's probably a good idea to do a lint check.

ok, i have added it back and a requirements file

**Comment by itsToggle** [comment]
Awesome! Thank you so much!

**Comment by itsToggle** [comment]
Hi, I've updated the script with some higher priority bug fixes since you've added this pull request and sadly I can't merge it automatically anymore. I could do the lint check myself, but I would like to mention you in the contributors section :)

**Comment by themegaphoenix** [comment]
> 

thanks! will do tonight

**Pull request closed without merging**
